### PR TITLE
Wietze add blocks: elemwise Reduce (max, mean etc), misc.MaskAbove, MaskRandom and radius arg in spatial.Dilate

### PR DESCRIPTION
**Pull request by wietzesuijker**

### CODE REVIEW

**Comment by wsuijker** [comment]
Ideally the elemwise reducers work similar to temporal,TemporalAggregate. I didn't manage to make that work (yet).

**Comment by wsuijker** [comment]
The reducers are also needed for a spatial.Move block. E.g. effects of new objects can spatially overlap. In such a block one layer, e.g. the effect of adding a tree to a map, can be moved to a list of new locations. The new locations might overlap, in these cases I want to apply stats like sum, max, or weighted mean.

**Comment by caspervdw** [comment]
This should be rebased using work on #49

**Comment by caspervdw** [comment]
Closing , superseded by #66

**Pull request closed without merging**
