### PR TITLE
add product to reduction statistics (as described in docstring)

### PR DESCRIPTION
**Pull request by wietzesuijker**

### CODE REVIEW

**Comment by wietzesuijker** [comment]
@caspervdw

**Comment by caspervdw** [comment]
Thanks for the addition! Can you adapt the relevant docstrings and add unittests?

**Comment by wietzesuijker** [comment]
Done. Docstring was already there. Thanks for the tips on pytest

**Comment by caspervdw** [comment]
I see, thanks for the update. One more thing is `CHANGES.rst`. Could you add a line there?

**Pull request merged**
